FROM node:16.14.0-alpine as build

WORKDIR /usr/src/app
COPY niver-web/. ./
RUN npm install
COPY . ./
RUN npm run build

# Stage - Production
FROM nginx:1.21.6-alpine
COPY --from=build /usr/src/app/build /usr/share/nginx/html
COPY nginx-conf/nginx2.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]