name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 16.14
        uses: actions/setup-node@v1
        with:
          node-version: "16.14"
      - name: Install yarn and run unittest
        run: |
          cd niver-web
          yarn
          yarn test --passWithNoTests
        env:
          CI: true
      - name: Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: my_github_username/my_repository_name/my_image_name/my_image_name
          registry: docker.pkg.github.com
          username: ${{ secrets.USER_NAME_GITHUB }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Dockerfile-prod
          tags: latest
